### ISSUE TITLE
Configuring with 64 output channels (with 64 channels per packet!) results in 0 Gb/s egress

### ISSUE THREAD

**Issue by radonnachie** [realtimeradio/vla-dev#25]
Configuration yaml:
```yaml
default:
    dts_lane_map:
        - [0,1,3,7,6,8,2,4,5,9,11,10] # Default for pipeline ID 0
        - [4,5,7,3,2,8,6,0,1,9,11,10] # Default for pipeline ID 1
packetizer:
    chans_per_packet: 64
    tuning_id_bitlength: 2
    source_port: 50000
    start_gbes: '192.168.65.128'
silent: ['ea13', 'ea24', 'ea23', 'ea14', 'ea04', 'ea03']
syncing: ['ea16']
antenna: ['ea08', 'ea21']
xengines:
  arp:
    # cosmic-gpu-0
    192.168.64.100: 0xb8cef6a642a1
    192.168.65.100: 0xb8cef6a64189
  chans:
    # Channel destinations are specified as:
    # ip-port: [[feng_ids], [first_chan, last_chan+1]]
    # cosmic-gpu-0
    192.168.64.100-50000:
            tuning_mask: 0
            # Give [x,y] to send channel range range(x,y)
            chan_range: [64,128]
    # cosmic-gpu-1
    192.168.65.100-50000:
            tuning_mask: 1
            # Give [x,y] to send channel range range(x,y)
            chan_range: [64,128]
```

Configuration output (looks normal):
```
(cosmic_vla) cosmic@cosmic-head:~/dev/COSMIC-VLA-PythonLibs/scripts/config_yaml$ configure_remotefpga.py ./fen_dual_ant_fullband.yaml 
.
.
.
[{'ip': '192.168.64.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [0]}, {'ip': '192.168.65.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [1]}]
Initializing block (writable): dts
Initializing block (writable): fpga
Initializing block (writable): sync
Initializing block (writable): delay
Initializing block (writable): lo
Initializing block (writable): noisegen
Initializing block (writable): sinegen
Initializing block (writable): input
Initializing block (writable): qsfp_a
Initializing block (writable): qsfp_b
Initializing block (writable): qsfp_c
Initializing block (writable): qsfp_d
Initializing block (writable): pfb
Initializing block (writable): autocorr
Initializing block (writable): eq
Initializing block (writable): eqtvg
Initializing block (writable): corr
Initializing block (writable): chanreorder
Initializing block (writable): eth0
Performing software global reset
Updating telescope time
pipeline0_sync - Detected sync period 12800000.0 (2^23.6) clocks
pipeline0_sync - Detected sync period is 50.000 milliseconds
pipeline0_sync - Last sync pulse arrived at time 1663855073.55005
pipeline0_sync - Sync pulses offset from NTP by 49 us
pipeline0_sync - Next sync_clocks 425946898854400000 % 8192 = 4096 == 0
pipeline0_sync - Offset of 0.0 ns (0 samples) applied (requested 0.0 ns rounded from 0.0 samples, to the nearest multiple of 8192)
pipeline0_sync - Loaded new telescope time (425946898854400000) for Thu Sep 22 13:57:53 2022 (1663855073.6500)
pipeline0_sync - Load completed at 1663855073.6106
pipeline0_sync - Internal TT loaded with 589.42 milliseconds to spare
Disabling EQ TVGs...
Arming sync generators
Validated tt_of_sync: 425946898867200000
assigning dest {'ip': '192.168.64.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [0]}; ant 0, chan 64
assigning dest {'ip': '192.168.64.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [0]}; ant 1, chan 64
skipping channel start 64 for input 1 because it isnt in the feng_ids list
assigning dest {'ip': '192.168.65.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [1]}; ant 0, chan 64
assigning dest {'ip': '192.168.65.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [1]}; ant 1, chan 64
skipping channel start 64 for input 1 because it isnt in the feng_ids list
Enabling Ethernet output
Startup of pcie3d complete
Configuring ea22... http://cosmic-fpga-2:6000/remoteobjects/
        pcie3e #1

[{'ip': '192.168.64.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [4]}, {'ip': '192.168.65.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [5]}]
Initializing block (writable): dts
Initializing block (writable): fpga
Initializing block (writable): sync
Initializing block (writable): delay
Initializing block (writable): lo
Initializing block (writable): noisegen
Initializing block (writable): sinegen
Initializing block (writable): input
Initializing block (writable): qsfp_a
Initializing block (writable): qsfp_b
Initializing block (writable): qsfp_c
Initializing block (writable): qsfp_d
Initializing block (writable): pfb
Initializing block (writable): autocorr
Initializing block (writable): eq
Initializing block (writable): eqtvg
Initializing block (writable): corr
Initializing block (writable): chanreorder
Initializing block (writable): eth0
Performing software global reset
Updating telescope time
pipeline1_sync - Detected sync period 12800000.0 (2^23.6) clocks
pipeline1_sync - Detected sync period is 50.000 milliseconds
pipeline1_sync - Last sync pulse arrived at time 1663855074.09978
pipeline1_sync - Sync pulses offset from NTP by -224 us
pipeline1_sync - Next sync_clocks 425946898995200000 % 8192 = 0 != 0
pipeline1_sync - Next sync_clocks 425946899008000000 % 8192 = 4096 == 0
pipeline1_sync - Offset of 0.0 ns (0 samples) applied (requested 0.0 ns rounded from 0.0 samples, to the nearest multiple of 8192)
pipeline1_sync - Loaded new telescope time (425946899008000000) for Thu Sep 22 13:57:54 2022 (1663855074.2500)
pipeline1_sync - Load completed at 1663855074.2105
pipeline1_sync - Internal TT loaded with 139.23 milliseconds to spare
Disabling EQ TVGs...
Arming sync generators
Validated tt_of_sync: 425946899020800000
assigning dest {'ip': '192.168.64.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [4]}; ant 0, chan 64
assigning dest {'ip': '192.168.64.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [4]}; ant 1, chan 64
skipping channel start 64 for input 1 because it isnt in the feng_ids list
assigning dest {'ip': '192.168.65.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [5]}; ant 0, chan 64
assigning dest {'ip': '192.168.65.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [5]}; ant 1, chan 64
skipping channel start 64 for input 1 because it isnt in the feng_ids list
Enabling Ethernet output
Startup of pcie3e complete
```

**Comment by radonnachie** [comment]
In the second scenario this is piquant:
```
assigning dest {'ip': '192.168.64.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [0]}; ant 0, chan 64
assigning dest {'ip': '192.168.64.100', 'port': 50000, 'start_chan': 64, 'nchan': 64, 'feng_ids': [0]}; ant 0, chan 96
```

With pktnchan=32, this is correct as the channel range specified is [64, 128] (just to keep us on our toes).

So it would appear that this might be a firmware issue (some --counter > 0 stuff?)

**Comment by jack-h** [comment]
Does it work with 64-chans per packet in any output configuration. E.g. 256 channels / 64 channels per packet? (The thinking here just being -- is this a packet size issue?)
and/or Does it work for other values of n_chan = n_chan_per_packet -- e.g. 32 chans / 32 chans per packet?

The output of `_read_headers` ( https://github.com/realtimeradio/vla-dev/blob/e8a3869828d3d6a4ec40f2378fca71c4f2437109/software/control_sw/src/blocks/packetizer.py#L138 ) would be informative.

**Comment by radonnachie** [comment]
We typically use 64 channels per packet, so it works when the number of overall channels is > 64. I'll try the 32/32 scenario.

**Comment by radonnachie** [comment]
the 32/32 scenario also led to no data egress. I'll look to configure with 64/64 and then get the _read_headers printout

**Comment by radonnachie** [comment]
I see some data leaking through mind you, but following is the `_read_headers() if header['valid]` from an antenna:

```
[{'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': True, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 0, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': True, 'dest_ip': '192.168.64.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': True, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': False, 'dest_ip': '192.168.65.100', 'dest_port': 50000}, {'feng_id': 1, 'chans': 0, 'n_chans': 64, 'is_time_fastest': True, 'is_8_bit': True, 'first': False, 'valid': True, 'last': True, 'dest_ip': '192.168.65.100', 'dest_port': 50000}]
```

**Comment by jack-h** [comment]
Thanks. So broadly this currently seems to be: When the number of output
channels per packet is the same as the total number of channels, nothing is
sent. That at least seems like a plausible corner-case.

**Comment by radonnachie** [comment]
That's my understanding of it. At least there is a work around in the meanwhile.

**Comment by jack-h** [comment]
Update 1:

**Comment by jack-h** [comment]
From the `kutleng_skarab2_bsp_firmware` repo:

![image](https://user-images.githubusercontent.com/1402492/203778916-7512b061-5324-4439-a93e-98e3ab0744ed.png)

Think this is an internal 100G issue. Packet rate is so low something is timing out

**Comment by jack-h** [comment]
This config file _does_ work:
```
fengines:
    chans_per_packet: 64
    dts_lane_map:
        - [0,1,3,2,4,5,7,6,8,9,11,10] # Default for pipeline ID 0
        - [4,5,7,6,0,1,3,2,8,9,11,10] # Default for pipeline ID 1
    pcie65:
        0:
            feng_ids: [0, 1]
            gbes: ['192.168.64.20']
            source_port: 10000
        1:
            feng_ids: [2, 3]
            gbes: ['192.168.64.21']
            source_port: 10000
            #dts_lane_map: [8,9,2,3,10,11,4,5,0,1,6,7] Override default if necessary

xengines:
  arp:
    # cosmic-gpu-0
    192.168.64.100: 0xb8cef6a642a1
    192.168.65.100: 0xb8cef6a64189
  chans:
    # Channel destinations are specified as:
    # ip-port: [[feng_ids], [first_chan, last_chan+1]]
    # cosmic-gpu-0
    192.168.65.100-11111:
            # The feng_mask/feng_range_mask entries filter the feng_ids
            # of the pipelines. The feng_ids that will actually be sent
            # to the xengine-destination is the union of the mask and the
            # pipeline's feng_ids list.

            # Send specific Feng IDs. This key overrides feng_range
            # feng_mask: [0,1,2,3,4,5,6,7]
            # Send a range of fengs. If [x,y] is given, send range(x,y).
            # If [x,y,z] is given, send range(x,y,z)
            feng_range_mask: [0,8,2] # Even Feng-IDs
            # Give [x,y] to send channel range range(x,y)
            chan_range: [64,128]
    # cosmic-gpu-0
    192.168.65.100-22222:
            feng_range_mask: [1,8,2] # Odd Feng-IDs
            # Give [x,y] to send channel range range(x,y)
            chan_range: [64,128]
    192.168.64.100-11111:
            feng_range_mask: [0,8,2] # Odd Feng-IDs
            # Give [x,y] to send channel range range(x,y)
            chan_range: [128,192]
    192.168.64.100-22222:
            feng_range_mask: [1,8,2] # Odd Feng-IDs
            # Give [x,y] to send channel range range(x,y)
            chan_range: [128,192]
```

I.e., 64 chans per packet with 64 chans per destination is fine, as long as at least 128 channels are sent in total.
The issue appears to be associated with too long spent idle between packets.

I've added a DROP mac address rule for the mac `0xdeaddeaddead` (On the 100G switch: `mac address-table static dead.dead.dead vlan 1 drop`), so one workaround now is to send dummy channels to this address. Eg:

```
fengines:
    chans_per_packet: 64
    dts_lane_map:
        - [0,1,3,2,4,5,7,6,8,9,11,10] # Default for pipeline ID 0
        - [4,5,7,6,0,1,3,2,8,9,11,10] # Default for pipeline ID 1
    pcie65:
        0:
            feng_ids: [0, 1]
            gbes: ['192.168.64.20']
            source_port: 10000
        1:
            feng_ids: [2, 3]
            gbes: ['192.168.64.21']
            source_port: 10000
            #dts_lane_map: [8,9,2,3,10,11,4,5,0,1,6,7] Override default if necessary

xengines:
  arp:
    # cosmic-gpu-0
    192.168.64.100: 0xb8cef6a642a1
    192.168.65.100: 0xb8cef6a64189
    192.168.64.0  : 0xdeaddeaddead
  chans:
    # Channel destinations are specified as:
    # ip-port: [[feng_ids], [first_chan, last_chan+1]]
    # cosmic-gpu-0
    192.168.65.100-11111:
            # The feng_mask/feng_range_mask entries filter the feng_ids
            # of the pipelines. The feng_ids that will actually be sent
            # to the xengine-destination is the union of the mask and the
            # pipeline's feng_ids list.

            # Send specific Feng IDs. This key overrides feng_range
            # feng_mask: [0,1,2,3,4,5,6,7]
            # Send a range of fengs. If [x,y] is given, send range(x,y).
            # If [x,y,z] is given, send range(x,y,z)
            feng_range_mask: [0,8,2] # Even Feng-IDs
            # Give [x,y] to send channel range range(x,y)
            chan_range: [64,128]
    # cosmic-gpu-0
    192.168.65.100-22222:
            feng_range_mask: [1,8,2] # Odd Feng-IDs
            # Give [x,y] to send channel range range(x,y)
            chan_range: [64,128]
    192.168.64.0-11111:
            feng_range_mask: [0,8,2] # Odd Feng-IDs
            # Give [x,y] to send channel range range(x,y)
            chan_range: [128,192]
    192.168.64.0-22222:
            feng_range_mask: [1,8,2] # Odd Feng-IDs
            # Give [x,y] to send channel range range(x,y)
            chan_range: [128,192]
```

Note that the IP should still be on the FPGA 100G's subnet, else the packet will be sent to the gateway, with a non-drop MAC.
